-- =========================================================
-- Library Management System - PostgreSQL schema
-- =========================================================
-- Same tables/columns/relationships as the original SQLite schema.
-- Deliberately unchanged so no business logic had to change:
--   * dates stay TEXT in the same "YYYY-MM-DD HH:MM:SS" format
--   * flags (returned, return_requested, read, ...) stay INTEGER 0/1
--   * borrow_records.book_id / user_email are NOT foreign keys, exactly as
--     before: borrow history must survive deleting a book or a user (your
--     data has such a record: borrow #1 for the deleted book id 1).
-- Auto-numbered columns use IDENTITY ... BY DEFAULT so the migration can
-- load the existing ids unchanged; new rows then continue after them.
-- users.seq / books.seq only preserve the order rows were added (SQLite
-- listed rows in insertion order; PostgreSQL has no implicit order).
-- Idempotent: safe to run more than once.
-- =========================================================

CREATE TABLE IF NOT EXISTS users (
    seq      BIGINT GENERATED ALWAYS AS IDENTITY,   -- keeps insertion order
    email    TEXT PRIMARY KEY,
    name     TEXT,
    password TEXT,              -- bcrypt hash
    role     TEXT               -- 'user' | 'librarian' | 'admin'
);

CREATE TABLE IF NOT EXISTS books (
    seq       BIGINT GENERATED ALWAYS AS IDENTITY,  -- keeps insertion order
    book_id   TEXT PRIMARY KEY,
    book_name TEXT,
    author    TEXT,
    publisher TEXT,
    isbn      TEXT,
    category  TEXT,
    copies    INTEGER
);

CREATE TABLE IF NOT EXISTS borrow_records (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email            TEXT,
    book_id               TEXT,
    book_name             TEXT,
    author                TEXT,
    category              TEXT,
    borrowed_date         TEXT,
    due_date              TEXT,
    returned              INTEGER,
    returned_date         TEXT,
    return_requested      INTEGER,
    return_requested_date TEXT,
    book_condition        TEXT,
    days_late             INTEGER,
    late_fine             INTEGER,
    damage_fine           INTEGER,
    lost_fine             INTEGER,
    total_fine            INTEGER,
    fine_status           TEXT,
    fine_paid_date        TEXT,
    renewal_count         INTEGER NOT NULL DEFAULT 0,
    last_renewed_at       TEXT
);

CREATE TABLE IF NOT EXISTS renewal_requests (
    renewal_request_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrow_id          INTEGER NOT NULL,
    user_email         TEXT NOT NULL,
    book_id            TEXT,
    requested_at       TEXT NOT NULL,
    requested_due_date TEXT,
    status             TEXT NOT NULL DEFAULT 'PENDING',
    librarian_email    TEXT,
    reviewed_at        TEXT,
    remarks            TEXT,
    FOREIGN KEY (borrow_id)  REFERENCES borrow_records(id),
    FOREIGN KEY (user_email) REFERENCES users(email),
    FOREIGN KEY (book_id)    REFERENCES books(book_id)
);

CREATE TABLE IF NOT EXISTS system_settings (
    setting_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_name  TEXT UNIQUE NOT NULL,
    setting_value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS waitlist (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email     TEXT,
    user_name      TEXT,
    book_id        TEXT,
    book_name      TEXT,
    requested_date TEXT
);

CREATE TABLE IF NOT EXISTS notifications (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email     TEXT,
    message        TEXT,
    type           TEXT,
    created_date   TEXT,
    "read"         INTEGER,
    title          TEXT,
    book_name      TEXT,
    fine_amount    INTEGER,
    days_late      INTEGER,
    book_condition TEXT,
    reason         TEXT
);

CREATE TABLE IF NOT EXISTS password_reset_otps (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email            TEXT NOT NULL,
    otp_hash         TEXT NOT NULL,
    created_at       TEXT NOT NULL,
    expires_at       TEXT NOT NULL,
    attempts         INTEGER NOT NULL DEFAULT 0,
    verified         INTEGER NOT NULL DEFAULT 0,
    used             INTEGER NOT NULL DEFAULT 0,
    reset_expires_at TEXT
);

INSERT INTO system_settings (setting_name, setting_value)
VALUES ('BORROW_DURATION_DAYS', '14')
ON CONFLICT (setting_name) DO NOTHING;

INSERT INTO system_settings (setting_name, setting_value)
VALUES ('RENEWAL_DURATION_DAYS', '7')
ON CONFLICT (setting_name) DO NOTHING;
